[tool.poetry]
name = "tech"
version = "0.1.0"
description = ""
authors = ["Dibyendu Tiwary <dibyendu.tiwary@vacasa.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
